services:
  - type: web
    name: nextjs-chatbot
    runtime: node
    plan: standard # 30人の同時アクセスにはStandardプラン以上を推奨
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: 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 # ここにAPIキーを設定
        sync: false # ダッシュボードで安全に設定するためsyncしない
    scaling:
      minInstances: 1
      maxInstances: 3 # 最大3インスタンスまで自動でスケールアウト
      targetCPUPercent: 60 # CPU使用率が60%を超えたら新しいインスタンスを追加
